### PR TITLE
Add borg as an alternate way to takes backups

### PR DESCRIPTION
**Pull request by Aeredren**
Borg take incremental backups and allow a smaller footprints for a greater number of archives.

As I needed this feature I thought I would push it upstream, maybe other will find it cool.

### CODE REVIEW

**Comment by Edenhofer** [comment]
Thanks for the contribution! I like the idea of extending the backup functionality and I personally use borg a lot too.

However, the current implementation introduces a lot of duplicate code instead of generalizing existing functionality. Please improve the functionality of `backup_files` and `backup_restore` instead of introducing slightly modified clones of these functions.

**Comment by Aeredren** [comment]
Okay, will do :)

I was also wondering if we should abstract the backup/restauration process in order to let an easy addition of any backup utility ? The backup function would deal with all the "disable / enable saves" and call the backup utility given as an argument.

I'll try things and update the MR for further feedback ;)

**Comment by Edenhofer** [comment]
Great! Yes, there should be no borg specific code or flags flying around. Everything should be sufficiently generic such that users could just as well choose any other backup tool.

**Comment by Aeredren** [comment]
Done !

Now the backup and restore methods are "backup tool agnostic".

All code relative to a specific backup tool is in the conditional, line 481. In order to add another backup tool, one need to define those 5 functions in this conditional: 

- ```make_backup```
- ```prune_backup```
- ```list_backup```
- ```check_backup_by_name```
- ```restore_backup```

One can use the flags ```BACKUP_FLAGS``` ```KEEP_BACKUPS``` and ```PRUNE_FLAGS``` to pass parameters to the backup tool

Tar is still the default and fallback option and no functionalities has been altered from the original program.

I tested the different functions for both tar and borg to make sure everything is working. It should be okay :)

Any feedback is welcome !

**Comment by Aeredren** [comment]
Also, I did not follow your commit message style as I thought you would squash the commit when merging and choose a commit message to your liking ;)

**Comment by Aeredren** [comment]
Hey @Edenhofer  :) Whaddaya think of it ?
It is not a complete abstraction indeed as new tools needs to defines new function in the scripts but I couldn't make it work otherwise.

**Comment by Edenhofer** [comment]
I have to admit, I am still not that happy with the current implementation. I don't think one can say that it is generic nor is the code free of borg specific flags (looking at `PRUNE_FLAGS`).

While I really like Borg, I do think there are many more backup tools that might make sense for a Minecraft server. I do not want to special case Borg nor do I want to add 30-40ish lines per backup tool.

Do you think you could compress your use case into a single callback function? If so, I would propose to add a callback program to the backup functions such that the user can e.g. move the tar files into a Borg backup. Restoring from external backups would not be possible but it would be a minimally invasive change.

**Comment by Aeredren** [comment]
Hello,

Yes indeed, a callback to an external script might be a good idea.

What do you think of a "plugin-like" functionality to add backup tools. The main script deal with all the idling and restarting the minecraft server, and the presentation, but outsourced the backuping, restoring, listing to a script in plugin/nameofthebackuputility.sh

The only new official argument is BACKUP_METHOD, and I write a plugin/tar.sh and a plugin/borg.sh

And if a plugin need specific argument, one can always add its own section at the end of the config file with a "namespace" like BACKUP_METHOD_BORG_FOOBAR.

This way anyone can add backup utilities without touching to minecraftd.sh.

I'm not sure where the "plugin" directory should be installed. I'm thinking of sourcing /usr/share/minecraftd/plugin for integrated one, and /usr/local/share/minecraftd/plugin for user defined one. Maybe I should also add "PATH" variable for plugin directory.

What do you think of this architecture ?

P.S. : sorry for the back and forth, tell me if those iterations annoy you. I'm just trying to improve this tool I like, but I don't want to bother you with my bad development decision

**Comment by Aeredren** [comment]
On second though (if you are ok with adding this) we might as well keep the tar method in minecraftd.sh in order to always have it has a fallback. Outsourcing it like any other plugin is more uniform and backup method agnostic, but we never know what people might do with their filesystem.

This way, we might also not install those plugins anywhere, and so minecraftd does not create any new directories system-wide. I just do a PLUGIN_DIRECTORY variable, which default to something like SERVER_ROOT/minecraftd_backup_plugin/ and let user install or write the backup method they need.

It is the less intrusive I can think of. Plugins can have their own git repositories, but I personally think it would be best to have a plugin/ directory in this main git repository to centralized everything and let people be aware of the functionality. This is of course yours to choose, it is your git repo.

**Comment by Edenhofer** [comment]
No worries! I am genuinely struggling to come up with a neat interface myself. Doing this cleanly is trickier than I though. IMO bash just isn't great for splitting sources across files or having pluggable modules. I would rather keep everything to a single file if possible.

I think implementing restoring capabilities makes this all the more trickier. Taking backups can often be achieved with a simple one-linear but restoring them requires parsing the output of the backup tool. I think allowing custom backup tools shouldn't be too complicated but I am drawn toward requiring tar backups for the restore functionality.

Would you be happy with a simple `BACKUP_CALLBACK_POST` option that is called after the classic tar backup? You could extract the tar backup into a borg backup via this hook. However, we would not support restoring or backups outside of tar at all. This would mean that the whole borg backup logic would need to happen outside of the minecraft script and they would interface only via a generic callback.

**Comment by Aeredren** [comment]
Hi,
I agree, bash isn't good at plugin. I think the overhead of callback / pushback from a tar isn't worth it. And I think I took a wrong approach to this problem since the beginning.

minecraft-server core functionality is running a game server and giving a server_command entry point to the administrator. Its strength is its simplicity and straight-forwardness.

Tar backup is a neat addition but not a core functionnality. Backup is an administrator task.

My new opinion on the issue is : 
- We should stop twisting the tool to integrate every backup methods people may want
- I should write and publish a separate script to manage minecraft_server borg backup on my own.

This way minecraftd stay small and simple, and does one thing, and does it well.

IMO the issue can be closed. Sorry for those 2 pages of digital ink, I was too eager to contribute to stop sooner.

**Comment by Edenhofer** [comment]
Sorry for the long delay in responding!

I took a long look at the patch again and I think I agree with your assessment. The addition of an arguably better backup functionality complicates the code noticeably, but is not a core focus of the script overall. I would have been happy to merge a simple generic extension to the script, but since we can't come up with a generic yet simple way to add backup tools, maybe it's best to keep both the minecraft management script and the backup taking separate.

I very much appreciate your interest in contributing and am sure there will be more opportunities to do so in the future!

**Pull request closed without merging**
